In [1]:
tup = ()
tup

()

In [2]:
t1 = tuple()
t1

()

In [4]:
t1 = (1,2,5,6,10,3,33)
t1

(1, 2, 5, 6, 10, 3, 33)

In [6]:
t1.count(6)

1

In [7]:
t1.index(5)

2

In [8]:
for i in t1:
  print(i)

1
2
5
6
10
3
33


In [9]:
for i in enumerate(t1):
  print(i)

(0, 1)
(1, 2)
(2, 5)
(3, 6)
(4, 10)
(5, 3)
(6, 33)


In [10]:
sorted(t1)

[1, 2, 3, 5, 6, 10, 33]

In [11]:
sorted(t1,reverse=True)


[33, 10, 6, 5, 3, 2, 1]

In [13]:
s1 = set()
print(type(s1))

<class 'set'>


In [15]:
s2 = {}
print(type(s2))

<class 'dict'>


In [20]:
t3 = (3,5,8)
t3

(3, 5, 8)

In [21]:
del t3


In [26]:
s1 = set()
print(type(s1))
s1 = (3,5,6,9,4,1)
print(type(s1))

<class 'set'>
<class 'tuple'>


In [27]:
s3 = {6,2,8,1,9,1,0,66}
s3

{0, 1, 2, 6, 8, 9, 66}

In [28]:
s3.add('ili')
s3

{0, 1, 2, 6, 66, 8, 9, 'ili'}

In [29]:
s3.add(3)
s3

{0, 1, 2, 3, 6, 66, 8, 9, 'ili'}

In [1]:
d1 = dict()
type(d1)

dict

In [2]:
d1 = {1:'one',2:'two',3:'three',4:"test",5:"told"}
d1

{1: 'one', 2: 'two', 3: 'three', 4: 'test', 5: 'told'}

In [3]:
d1.items()

dict_items([(1, 'one'), (2, 'two'), (3, 'three'), (4, 'test'), (5, 'told')])

In [4]:
d1.keys()

dict_keys([1, 2, 3, 4, 5])

In [5]:
d1.values()

dict_values(['one', 'two', 'three', 'test', 'told'])

In [6]:
d1.get(3)

'three'

In [9]:
d1[2] = "correct"

In [10]:
d1

{1: 'one', 2: 'correct', 3: 'three', 4: 'test', 5: 'told'}

In [11]:
d1.update({3:"nine"})
d1

{1: 'one', 2: 'correct', 3: 'nine', 4: 'test', 5: 'told'}

In [1]:
range(3)

range(0, 3)

In [11]:
range(10)
list[range(10)]


list[range(0, 10)]

In [13]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
range(1,10,3)

range(1, 10, 3)

In [10]:
list(range(1,10,3))

[1, 4, 7]

In [14]:
A[2,3]
A

NameError: name 'A' is not defined

In [18]:
import numpy as np
A = np.array([2,3])
A
np.__version__


'2.0.2'

In [19]:
import sys
sys.version

'3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]'

In [20]:
myList = [1,2,3,4,5,6]
print(myList)
type(myList)

[1, 2, 3, 4, 5, 6]


list

In [21]:
arr = np.array(myList)
print(arr)
type(arr)

[1 2 3 4 5 6]


numpy.ndarray

In [22]:
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [57]:
np.random.randint(0,10,7)

array([8, 6, 2, 5, 4, 4, 5])